language: php
dist: trusty

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

matrix:
  allow_failures:
    - php: 7.0
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_script:
  - travis_retry composer self-update
  - composer require pimple/pimple:"~3.0" rougin/slytherin:"~0.9" symfony/config:"~2.8|~3.0" symfony/console:"~2.8|~3.0" symfony/dependency-injection:"~2.8|~3.0" symfony/http-kernel:"~2.8|~3.0" --dev
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' && $TRAVIS_PHP_VERSION != '7.0' ]]; then php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover; fi